language: go
dist: xenial

env:
  - GO111MODULE=on

go:
  - 1.x

git:
  depth: 3

# before_install:
#   - openssl aes-256-cbc -K $encrypted_53f656cbcdd0_key -iv $encrypted_53f656cbcdd0_iv
#     -in deploy_key.enc -out ./deploy_key -d
#   - eval "$(ssh-agent -s)"
#   - chmod 600 ./deploy_key
#   - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
#   - ssh-add ./deploy_key

install:
  - go get -u -v github.com/magefile/mage
  - curl -fL -o hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.63.0/hugo_extended_0.63.0_Linux-64bit.deb
  - sudo dpkg -i hugo.deb

script:
  - cd $TRAVIS_BUILD_DIR
  - "PATH=$GOPATH/bin:$PATH mage -v data build"

deploy:
  edge: true
  provider: "pages:git"
  repo: deanishe/deanishe.github.io
  target_branch: master
  local_dir: public
  # token: "$GITHUB_TOKEN"
  cleanup: false
  on:
    branch: master

