language: go

go:
  - 1.x

git:
  depth: 3

before_install:
  - openssl aes-256-cbc -K $encrypted_53f656cbcdd0_key -iv $encrypted_53f656cbcdd0_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key

install:
  - go get -u -d github.com/magefile/mage
  - cd $GOPATH/src/github.com/magefile/mage
  - go run bootstrap.go
  - cd $HOME
  - curl -fL -o hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_extended_0.53_Linux-64bit.deb
  - sudo dpkg -i hugo.deb
  # - git clone https://github.com/gohugoio/hugo.git
  # - cd hugo
  # - HUGO_BUILD_TAGS=extended mage -v install
  - cd $TRAVIS_BUILD_DIR
  - go GO111MODULE=on mod tidy -v
  - go GO111MODULE=on mod verify
  - go GO111MODULE=on mod vendor -v

script:
  - cd $TRAVIS_BUILD_DIR
  - "PATH=$GOPATH/bin:$PATH GO111MODULE=on mage -v data build"

deploy:
  skip_cleanup: true
  provider: pages
  repo: deanishe/deanishe.github.io
  target-branch: master
  local_dir: public
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master

