language: go
os: linux
dist: xenial

env:
  - GO111MODULE=on

go:
  - 1.x

git:
  depth: 3

install:
  - go get -u -v github.com/magefile/mage
  - curl -fL -o hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.63.0/hugo_extended_0.63.0_Linux-64bit.deb
  - sudo dpkg -i hugo.deb

script:
  - cd $TRAVIS_BUILD_DIR
  - "PATH=$GOPATH/bin:$PATH mage -v data build"

deploy:
  edge: true
  provider: pages
  repo: deanishe/deanishe.github.io
  target_branch: master
  local_dir: public
  cleanup: false
  on:
    branch: master

