language: go

go:
  - 1.x

before_install:
  - openssl aes-256-cbc -K $encrypted_53f656cbcdd0_key -iv $encrypted_53f656cbcdd0_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key

install:
  - go get -u -d github.com/magefile/mage
  - cd $GOPATH/src/github.com/magefile/mage
  - go run bootstrap.go
  - cd $HOME
  - git clone https://github.com/gohugoio/hugo.git
  - cd hugo
  - HUGO_BUILD_TAGS=extended mage -v install
  - cd $TRAVIS_BUILD_DIR
  - GO111MODULE=on go mod tidy -v
  - GO111MODULE=on go mod verify
  - GO111MODULE=on go mod vendor -v

script:
  - cd $TRAVIS_BUILD_DIR
  - "PATH=$GOPATH/bin:$PATH GO111MODULE=on mage -v data build"

deploy:
  skip_cleanup: true
  provider: pages
  repo: deanishe/deanishe.github.io
  target-branch: master
  local_dir: public
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master

