baseURL = "http://www.deanishe.net/"
languageCode = "en-GB"
title = "deanishe.net"

contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
theme = "alabastard"

canonifyURLs = false
relativeURLs = false

metadataFormat = "yaml"

paginate = 10

enableRobotsTXT = true

enableGitInfo = true

disqusShortname = ""
googleAnalytics = ""

[blackfriday]
	sourceRelativeLinksEval = false

[params]
	name = "deanishe.net"
	description = "dem Dean sein Zeug"

	custom_css = []
	custom_js  = []

	highlightjs = "css/highlight.css"
	favicons = "images/favicons"

	# Analytics
	piwikURL = "deanishe.net/piwik"
	piwikSiteID = 2

	# Social
	githubUsername   = "deanishe"
	githubRepo   = "deanishe.github.io"
	githubBanner = false
	twitterUsername = "deanishe"

	# Homepage
	homepageRecentEvents = 5
	homepageRecentLinks = 5
	homepageRecentPosts = 5

	# Links
	pinboardMaxPosts = 15

[params.sidebar]
	logo = "images/deanishe-128.png"

	githubButton  = false
	travisButton  = false
	codecovButton = false
	gratipay = ""

	show_relations = false

[params.footer]
	copyright = "[@deanishe](https://twitter.com/deanishe)"
	show_powered_by = false

[permalinks]
	# Any item with "type=toplevel" will be placed at the top level
	toplevel = "/:filename/"

[taxonomies]
	tag = "tags"
	category = "categories"
	platform = "platforms"
