baseurl = "http://localhost:1313/"
languageCode = "en-GB"
metadataFormat = "yaml"
title = "deanishe.net"
theme = "alabastard"

paginate = 10

enableRobotsTXT = true

enableGitInfo = true

disqusShortname = ""
googleAnalytics = ""

[blackfriday]
	sourceRelativeLinksEval = true

[params]
	name = "deanishe.net"
	description = "dem Dean sein Zeug"

	custom_css = []
	custom_js  = []

	highlightjs = "css/highlight.css"
	favicons = "images/favicons"

	# Analytics
	piwikURL = "deanishe.net/piwik"
	piwikSiteID = 2

	# Social
	# github_user   = "deanishe"
	# github_repo   = "deanishe.github.io"
	githubUsername   = "deanishe"
	githubRepo   = "deanishe.github.io"
	githubBanner = false
	twitterUsername = "deanishe"

[params.sidebar]
	logo = "images/deanishe-128.png"


	githubButton  = false
	travisButton  = false
	codecovButton = false
	gratipay = ""

	show_relations = false

[params.footer]
	copyright = "[@deanishe](https://twitter.com/deanishe)"
	show_powered_by = false

[permalinks]
	page = "/:filename/"

[taxonomies]
	tag = "tags"
	category = "categories"
	platform = "platforms"
